
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.function.UnaryOperator;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Admin_Layout extends javax.swing.JFrame {
    private final ArrayList<Student> list = new ArrayList<>();
    private int CurrentIndex = -1;
    Student st = new Student();
    private final String header[] ={"Ma SV", "Ten SV", "Ngay Sinh", "Thang Sinh", "Nam Sinh", "Gioi Tinh", "SDT", "Dia Chi", "Khoa", "Chuyen Nganh", "CMT", "Ngay Cap", "Noi Cap", "Ngay Nhap Hoc", "Trang Thai", "Hoc Ki", "Email", "Hinh Anh"};
    private final DefaultTableModel modelTableSinhVien = new DefaultTableModel(header,0);
    
    /**
     * Creates new form QLSV
     */
    public Admin_Layout() {
        initComponents();
        loadData();
        loadDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sex = new javax.swing.ButtonGroup();
        Level = new javax.swing.ButtonGroup();
        FileChooser = new javax.swing.JFileChooser();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        txtTenSV = new javax.swing.JTextField();
        cbNgay = new javax.swing.JComboBox<>();
        cbThang = new javax.swing.JComboBox<>();
        cbNam = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        cbGioiTinh = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cbChuyenNganh = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtCMT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbNgayCap = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtNoiCap = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbNgayNhapHoc = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtKhoa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtHocKi = new javax.swing.JTextField();
        cbTrangThai = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSinhVien = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lblAvatar = new javax.swing.JLabel();
        btnBrowser = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnShowGrade = new javax.swing.JButton();
        txtSource = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        bntTimKiem = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnLast = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Students Management");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 90));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Information", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel1.setText("Mã Sinh Viên: ");

        jLabel2.setText("Tên Sinh Viên: ");

        jLabel3.setText("Ngày Sinh: ");

        jLabel4.setText("Giới Tính: ");

        jLabel5.setText("Số Điện Thoại: ");

        jLabel6.setText("Email: ");

        jLabel8.setText("Địa Chỉ: ");

        cbNgay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dd", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mm", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbThangActionPerformed(evt);
            }
        });

        cbNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yyyy", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000" }));

        txtDiaChi.setColumns(20);
        txtDiaChi.setRows(5);
        jScrollPane1.setViewportView(txtDiaChi);

        cbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Gioi Tinh---", "Nam ", "Nu" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cbNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbThang, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtSDT)
                                .addComponent(txtEmail)
                                .addComponent(txtTenSV)
                                .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbThang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(cbGioiTinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 440, 380));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Information Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel18.setText("Khóa: ");

        jLabel20.setText("Chuyên ngành: ");

        cbChuyenNganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----Chuyen Nganh----", "Ung Dung Phan Mem", "Lap Trinh Android", "Lap Trinh Web", "Do Hoa", "Du lich- Nha Hang-Khach San", " " }));

        jLabel9.setText("CMT: ");

        jLabel10.setText("Ngày Cấp: ");

        cbNgayCap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yyyy", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2012", "2013", "2014", "2015", "2016" }));

        jLabel11.setText("Nơi Cấp: ");

        jLabel13.setText("Ngày Nhập Học: ");

        cbNgayNhapHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yyyy", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2012", "2013", "2014", "2015", "2016" }));

        jLabel14.setText("Trạng Thái: ");

        jLabel15.setText("Học Kì: ");

        txtHocKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHocKiActionPerformed(evt);
            }
        });

        cbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Trang Thai---", "HDI", "Tam Ngung", "Hoc Lai" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCMT)
                        .addComponent(txtNoiCap)
                        .addComponent(cbNgayNhapHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbNgayCap, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbChuyenNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHocKi, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbChuyenNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCMT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNgayCap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoiCap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNgayNhapHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(cbTrangThai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHocKi, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 400, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        tblSinhVien.setAutoCreateRowSorter(true);
        tblSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "StudentID", "Full Name", "Date Of Birth", "Sex", "Email", "Number Phone", "Address", "Lock", "Specialized", "Passport", "Day range", "Issued by", "Day admission", "Level", "Semester"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSinhVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSinhVien);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1218, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 1250, 140));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Avatar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setText("Avatar");

        btnBrowser.setText("Browser");
        btnBrowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBrowser)
                .addGap(36, 36, 36))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lblAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBrowser))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 170, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 110, 120, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "System", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 51, 0))); // NOI18N

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 350, 120, -1));

        btnShowGrade.setText("Show Grade");
        btnShowGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowGradeActionPerformed(evt);
            }
        });
        getContentPane().add(btnShowGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 120, 40));

        txtSource.setEditable(false);
        txtSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSourceActionPerformed(evt);
            }
        });
        getContentPane().add(txtSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 670, 430, 40));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm Kiếm"));

        bntTimKiem.setText("Tìm Kiếm");
        bntTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bntTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtTimKiem))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 430, -1));

        jLabel7.setText("Source Image: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 90, 40));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Button"));

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrev.setText("Prev");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 630, 520, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadData(){
        try{
            Connection conn=null;
            Statement stmt=null;
            //connection databse
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/qlsv_ps04107","root", "");
            //Execute a query
            stmt = conn.createStatement();
            String sql = "Select*from sinhvien";
            //dat cau lenh truy van o day...
            ResultSet rs = stmt.executeQuery(sql);
            JOptionPane.showMessageDialog(this, "Connection successfully.", "Message", JOptionPane.INFORMATION_MESSAGE);
            //Doc du lieu tu database...
            while(rs.next()){
                String MaSV = rs.getString("MaSV");
                String TenSV = rs.getString("TenSV");
                String NgSinh = rs.getString("NgaySinh");
                String ThangSinh = rs.getString("ThangSinh");
                String NamSinh = rs.getString("NamSinh");
                String GioiTinh = rs.getString("GioiTinh");
                String SDT = rs.getString("SDT");
                String DiaChi = rs.getString("DiaChi");
                String Khoa = rs.getString("Khoa");
                String ChuyenNganh = rs.getString("ChuyenNganh");
                String CMT  = rs.getString("CMT");
                String NgCap = rs.getString("NgayCap");
                String NoiCap = rs.getString("NoiCap");
                String NgNhapHoc = rs.getString("NgayNhapHoc");
                String TrangThai = rs.getString("TrangThai");
                String HocKi = rs.getString("HocKi");
                String HinhAnh = rs.getString("HinhAnh");
                String Email = rs.getString("Email");
                //Them vao doi tuong vao list
                Student st = new Student(MaSV, TenSV, NgSinh, ThangSinh, NamSinh, Email, SDT, DiaChi, Khoa, ChuyenNganh, CMT, NgCap, NoiCap, NgNhapHoc, HocKi, HinhAnh, GioiTinh, TrangThai);
                //System.out.println(st.getEmail());
                list.add(st);
                //doc du lieu len from  
            }
            CurrentIndex=0;
            DisplayStudent();
            rs.close();
            stmt.close();
            conn.close();
        }catch(SQLException se){
            JOptionPane.showMessageDialog(this, "Ket noi den database that bai");
        }
    }
    private void loadDataToTable(){

        try{
            Connection conn = null;
            Statement stmt = null;
            ResultSet rs = null;
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/qlsv_ps04107","root", "");
            String sql = "Select*from sinhvien";
            stmt = conn.createStatement();
            rs = stmt.executeQuery(sql);
            Vector sv = null;
            modelTableSinhVien.setRowCount(0);
            while(rs.next()){
                sv = new Vector();
                sv.add(rs.getString("MaSV"));
                sv.add(rs.getString("TenSV"));
                sv.add(rs.getString("NgaySinh"));
                sv.add(rs.getString("ThangSinh"));
                sv.add(rs.getString("NamSinh"));
                sv.add(rs.getString("GioiTinh"));
                sv.add(rs.getString("SDT"));
                sv.add(rs.getString("DiaChi"));
                sv.add(rs.getString("Khoa"));
                sv.add(rs.getString("ChuyenNganh"));
                sv.add(rs.getString("CMT"));
                sv.add(rs.getString("NgayCap"));
                sv.add(rs.getString("NoiCap"));
                sv.add(rs.getString("NgayNhapHoc"));
                sv.add(rs.getString("TrangThai"));
                sv.add(rs.getString("HocKi"));
                sv.add(rs.getString("Email"));
                sv.add(rs.getString("HinhAnh"));
                modelTableSinhVien.addRow(sv);
            }
            tblSinhVien.setModel(modelTableSinhVien);
        }catch(SQLException se){
            se.printStackTrace();
        }
    }
    private void DisplayStudent(){
        st = list.get(CurrentIndex);
        txtMaSV.setText(st.getMaSV());
        txtTenSV.setText(st.getTenSV());
        cbNgay.setSelectedItem(st.getNgSinh());
        cbThang.setSelectedItem(st.getThSinh());
        cbNam.setSelectedItem(st.getNamSinh());
        cbGioiTinh.setSelectedItem(st.getGioiTinh());
        txtEmail.setText(st.getEmail());
        txtSDT.setText(st.getSDT());
        txtDiaChi.setText(st.getDiaChi());
        txtKhoa.setText(st.getKhoa());
        cbChuyenNganh.setSelectedItem(st.getChuyenNganh());
        txtCMT.setText(st.getCMT());
        cbNgayCap.setSelectedItem(st.getNgCap());
        txtNoiCap.setText(st.getNoiCap());
        cbNgayNhapHoc.setSelectedItem(st.getNgNhapHoc());
        cbTrangThai.setSelectedItem(st.getTrangThai());
        txtHocKi.setText(String.valueOf(st.getHocKi()));
        txtSource.setText(st.getHinhAnh());
        lblAvatar.setIcon(new ImageIcon(st.getHinhAnh()));
    }
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        txtMaSV.setText("");
        txtTenSV.setText("");
        cbNgay.setSelectedItem("dd");
        cbThang.setSelectedItem("mm");
        cbNam.setSelectedItem("yyyy");
        cbGioiTinh.setSelectedItem("---Gioi Tinh---");
        txtSDT.setText("");
        txtEmail.setText("");
        txtDiaChi.setText("");
        txtKhoa.setText("");
        cbChuyenNganh.setSelectedItem("----Chuyen Nganh----");
        txtCMT.setText("");
        cbNgayCap.setSelectedItem("yyyy");
        txtNoiCap.setText("");
        cbNgayNhapHoc.setSelectedItem("yyyy");
        cbTrangThai.setSelectedItem("---Trang thai---");
        txtHocKi.setText("");
        txtSource.setText("");
        lblAvatar.setIcon(new ImageIcon());
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Are you exit?","Confirm", JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
            System.exit(0);
        }
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnShowGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowGradeActionPerformed
        // TODO add your handling code here:
        QL_DIEM  qld = new QL_DIEM();
        qld.setVisible(true);
    }//GEN-LAST:event_btnShowGradeActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int row = tblSinhVien.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(this, "Chooser row.", "Message", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        Connection conn = null;
        PreparedStatement ps = null;
        String sql = "update sinhvien set TenSV = ?, NgaySinh = ?, ThangSinh = ?, NamSinh = ?, GioiTinh = ?, SDT = ?, DiaChi = ?, Khoa = ?, ChuyenNganh = ?, CMT = ?, NgayCap = ?, NoiCap = ?, NgayNhapHoc = ?, TrangThai = ?, HocKi = ?,HinhAnh = ?, Email = ? where MaSV = ?";
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/qlsv_ps04107","root", "");
            ps = conn.prepareStatement(sql);
            ps.setString(1, String.valueOf(txtTenSV.getText()));         
            ps.setString(2, String.valueOf(cbNgay.getSelectedItem()));
            ps.setString(3, String.valueOf(cbThang.getSelectedItem()));
            ps.setString(4, String.valueOf(cbNam.getSelectedItem()));
            ps.setString(5, String.valueOf(cbGioiTinh.getSelectedItem()));
            ps.setString(6, String.valueOf(txtSDT.getText()));
            ps.setString(7, String.valueOf(txtDiaChi.getText()));
            ps.setString(8, String.valueOf(txtKhoa.getText()));
            ps.setString(9, String.valueOf(cbChuyenNganh.getSelectedItem()));
            ps.setString(10, String.valueOf(txtCMT.getText()));
            ps.setString(11, String.valueOf(cbNgayCap.getSelectedItem()));
            ps.setString(12, String.valueOf(txtNoiCap.getText()));
            ps.setString(13, String.valueOf(cbNgayNhapHoc.getSelectedItem()));
            ps.setString(14, String.valueOf(cbTrangThai.getSelectedItem()));
            ps.setString(15, String.valueOf(txtHocKi.getText()));
            ps.setString(16, String.valueOf(txtSource.getText()));
            ps.setString(17, String.valueOf(txtEmail.getText()));
            ps.setString(18, txtMaSV.getText());
            ps.execute();
            JOptionPane.showMessageDialog(this, "Cap nhat thanh cong." , "Thong bao", JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLException se){
            se.printStackTrace();
            JOptionPane.showMessageDialog(this, "Cap nhat khong thanh cong.", "Thong bao", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        modelTableSinhVien.setValueAt(txtMaSV.getText().trim(), row, 0);
        modelTableSinhVien.setValueAt(txtTenSV.getText().trim(), row, 1);
        modelTableSinhVien.setValueAt(cbNgay.getSelectedItem(), row, 2);
        modelTableSinhVien.setValueAt(cbThang.getSelectedItem(), row, 3);
        modelTableSinhVien.setValueAt(cbNam.getSelectedItem(), row, 4);
        modelTableSinhVien.setValueAt(cbGioiTinh.getSelectedItem(), row, 5);
        modelTableSinhVien.setValueAt(txtSDT.getText(), row, 6);
        modelTableSinhVien.setValueAt(txtDiaChi.getText().trim(), row, 7);
        modelTableSinhVien.setValueAt(txtKhoa.getText().trim(), row, 8);
        modelTableSinhVien.setValueAt(cbChuyenNganh.getSelectedItem(), row, 9);
        modelTableSinhVien.setValueAt(txtCMT.getText().trim(), row, 10);
        modelTableSinhVien.setValueAt(cbNgayCap.getSelectedItem(), row, 11);
        modelTableSinhVien.setValueAt(txtNoiCap.getText().trim(), row, 12);
        modelTableSinhVien.setValueAt(cbNgayNhapHoc.getSelectedItem(), row, 13);
        modelTableSinhVien.setValueAt(cbTrangThai.getSelectedItem(), row, 14);
        modelTableSinhVien.setValueAt(txtHocKi.getText().trim(), row, 15);
        modelTableSinhVien.setValueAt(txtEmail.getText().trim(), row, 16);
        modelTableSinhVien.setValueAt(txtSource.getText().trim(), row, 17);
        list.replaceAll((UnaryOperator<Student>) st);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void cbThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbThangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbThangActionPerformed

    private void tblSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSinhVienMouseClicked
        // TODO add your handling code here:
        int row = tblSinhVien.getSelectedRow();
        if(row<0){
            return;
        }
        txtMaSV.setText(tblSinhVien.getValueAt(row, 0).toString());
        txtTenSV.setText(tblSinhVien.getValueAt(row, 1).toString());
        cbNgay.setSelectedItem(tblSinhVien.getValueAt(row, 2).toString());
        cbThang.setSelectedItem(tblSinhVien.getValueAt(row, 3).toString());
        cbNam.setSelectedItem(tblSinhVien.getValueAt(row, 4).toString());
        cbGioiTinh.setSelectedItem(tblSinhVien.getValueAt(row, 5).toString());
        txtSDT.setText(tblSinhVien.getValueAt(row, 6).toString());
        txtDiaChi.setText(tblSinhVien.getValueAt(row, 7).toString());
        txtKhoa.setText(tblSinhVien.getValueAt(row, 8).toString());
        cbChuyenNganh.setSelectedItem(tblSinhVien.getValueAt(row, 9).toString());
        txtCMT.setText(tblSinhVien.getValueAt(row, 10).toString());
        cbNgayCap.setSelectedItem(tblSinhVien.getValueAt(row, 11).toString());
        txtNoiCap.setText(tblSinhVien.getValueAt(row, 12).toString());
        cbNgayNhapHoc.setSelectedItem(tblSinhVien.getValueAt(row, 13).toString());
        cbTrangThai.setSelectedItem(tblSinhVien.getValueAt(row, 14).toString());
        txtHocKi.setText(tblSinhVien.getValueAt(row, 15).toString());
        txtEmail.setText(tblSinhVien.getValueAt(row, 16).toString());
        txtSource.setText(tblSinhVien.getValueAt(row, 17).toString());
        lblAvatar.setIcon(new ImageIcon(txtSource.getText()));
        
    }//GEN-LAST:event_tblSinhVienMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Vector dataRow = new Vector();
        dataRow.add(txtMaSV.getText().trim());
        dataRow.add(txtTenSV.getText().trim());
        dataRow.add(cbNgay.getSelectedItem());
        dataRow.add(cbThang.getSelectedItem());
        dataRow.add(cbNam.getSelectedItem());
        dataRow.add(cbGioiTinh.getSelectedItem());
        dataRow.add(txtSDT.getText().trim());
        dataRow.add(txtDiaChi.getText().trim());
        dataRow.add(txtKhoa.getText().trim());
        dataRow.add(cbChuyenNganh.getSelectedItem());
        dataRow.add(txtCMT.getText());
        dataRow.add(cbNgayCap.getSelectedItem());
        dataRow.add(txtNoiCap.getText().trim());
        dataRow.add(cbNgayNhapHoc.getSelectedItem());
        dataRow.add(cbTrangThai.getSelectedItem());
        dataRow.add(txtHocKi.getText().trim());
        dataRow.add(txtSource.getText().trim());
        dataRow.add(txtEmail.getText().trim());
        modelTableSinhVien.addRow(dataRow);
        String sql = "Insert into sinhvien(MaSV, TenSV, NgaySinh, ThangSinh, NamSinh, GioiTinh, SDT, DiaChi, Khoa, ChuyenNganh, CMT, NgayCap, NoiCap, NgayNhapHoc, TrangThai, HocKi, HinhAnh, Email) Values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        Connection conn = null;
        PreparedStatement ps = null;
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/qlsv_ps04107","root", "");
            ps = conn.prepareStatement(sql);
            ps.setString(1, String.valueOf(txtMaSV.getText()));
            ps.setString(2, String.valueOf(txtTenSV.getText()));
            ps.setString(3, String.valueOf(cbNgay.getSelectedItem()));
            ps.setString(4, String.valueOf(cbThang.getSelectedItem()));
            ps.setString(5, String.valueOf(cbNam.getSelectedItem()));
            ps.setString(6,String.valueOf(cbGioiTinh.getSelectedItem()));
            ps.setString(7, String.valueOf(txtSDT.getText()));
            ps.setString(8, String.valueOf(txtDiaChi.getText()));
            ps.setString(9, String.valueOf(txtKhoa.getText()));
            ps.setString(10, String.valueOf(cbChuyenNganh.getSelectedItem()));
            ps.setString(11, String.valueOf(txtCMT.getText()));
            ps.setString(12, String.valueOf(cbNgayCap.getSelectedItem()));
            ps.setString(13, String.valueOf(txtNoiCap.getText()));
            ps.setString(14, String.valueOf(cbNgayNhapHoc.getSelectedItem()));
            ps.setString(15,String.valueOf(cbTrangThai.getSelectedItem()));
            ps.setInt(16, Integer.parseInt(txtHocKi.getText()));
            ps.setString(17, String.valueOf(txtSource.getText()));
            ps.setString(18, String.valueOf(txtEmail.getText()));
            ps.execute();
            JOptionPane.showMessageDialog(this, "Save successfully", "Message", JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLException se){
            JOptionPane.showMessageDialog(this, "Save faild", "Message", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = tblSinhVien.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(this, "Chooser row.", "Message", JOptionPane.YES_OPTION);
            return;
        }
        String sql = "DELETE FROM SinhVien Where MaSV = ?";
        Connection conn = null;
        PreparedStatement ps = null;
        try{ 
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/qlsv_ps04107","root", "");
            ps = conn.prepareStatement(sql);
            ps.setString(1, txtMaSV.getText());
            ps.execute();
            JOptionPane.showMessageDialog(this, "Delete successfully.", "Message" ,JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLException se){
            se.printStackTrace();
            JOptionPane.showMessageDialog(this, "Delete fail...", "Message", JOptionPane.INFORMATION_MESSAGE);
        }
        modelTableSinhVien.removeRow(row);
        list.remove(st);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowserActionPerformed
        // TODO add your handling code here:
        int result = FileChooser.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION){
            String fileName = FileChooser.getSelectedFile().getAbsolutePath();
            lblAvatar.setIcon(new ImageIcon(fileName));
            txtSource.setText(fileName);
        }
    }//GEN-LAST:event_btnBrowserActionPerformed

    private void txtSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSourceActionPerformed

    private void txtHocKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHocKiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHocKiActionPerformed

    private void bntTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntTimKiemActionPerformed
        // TODO add your handling code here:
        int i;
        String MaSV;
        MaSV = txtTimKiem.getText();
        for(i=0;i<list.size();i++){
            Student st = list.get(i);
            if(st.getMaSV().equalsIgnoreCase(MaSV)){
                JOptionPane.showMessageDialog(this, "Da tim thay", "Thong Bao", JOptionPane.INFORMATION_MESSAGE);
                CurrentIndex = i;
                DisplayStudent();
                break;
            }
        }
        if(i==list.size()){
            JOptionPane.showMessageDialog(this, "Khong tim thay sinh vien nay.", "Thong bao", JOptionPane.INFORMATION_MESSAGE);
            txtTimKiem.requestFocus();
        }
    }//GEN-LAST:event_bntTimKiemActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        CurrentIndex = list.size()-1;
        DisplayStudent();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        CurrentIndex++;
        if(CurrentIndex > list.size()){
            JOptionPane.showMessageDialog(this, "On the last page!!", "Message", JOptionPane.INFORMATION_MESSAGE);
        }
        DisplayStudent();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        CurrentIndex--;
        if(CurrentIndex < 0){
            JOptionPane.showMessageDialog(this, "On the first page!!", "Message",JOptionPane.INFORMATION_MESSAGE);
        }
        DisplayStudent();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        CurrentIndex = 0;
        DisplayStudent();
    }//GEN-LAST:event_btnFirstActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.ButtonGroup Level;
    private javax.swing.ButtonGroup Sex;
    private javax.swing.JButton bntTimKiem;
    private javax.swing.JButton btnBrowser;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnShowGrade;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbChuyenNganh;
    private javax.swing.JComboBox<String> cbGioiTinh;
    private javax.swing.JComboBox<String> cbNam;
    private javax.swing.JComboBox<String> cbNgay;
    private javax.swing.JComboBox<String> cbNgayCap;
    private javax.swing.JComboBox<String> cbNgayNhapHoc;
    private javax.swing.JComboBox<String> cbThang;
    private javax.swing.JComboBox<String> cbTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JTable tblSinhVien;
    private javax.swing.JTextField txtCMT;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHocKi;
    private javax.swing.JTextField txtKhoa;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtNoiCap;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSource;
    private javax.swing.JTextField txtTenSV;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

}
